apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-redis-cluster
  annotations: {}
  labels:
    argocd.argoproj.io/instance: redis-redis-cluster
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-redis-cluster
            port:
              number: 6379