apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-redis-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.6
    chart: redis-cluster
    helm:
      values: |
        cluster:
          externalAccess:
            enabled: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
