apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.2.1
    chart: redis
    helm:
      values: |
        cluster:
          externalAccess:
            enabled: true 
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
