---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: test
spec:
  encryptedData:
    dbpassword: AgBOysaoJrWhUkmHRlZ0P3rIEO2Kf/iyblJzkfd3QjA6rvEo6a+g74VpE5WSnzns/feD0f4TJr7+JY93gxtOXRODJ8Z4xNQl6HMjTmEpT7SVgb+cjkjXLAvOKg5wXYDM7Ol5T2QZIQRvtPliQX67kzO5XMBJhrRxY9smA05xJUqjE59PTI1yCGoKFXHO+AdBFLOjuGIGKj1I/zrqvp5/gkifAx9RPY5hXXkiCp5QkS0/kNZfGpZbL8DEWNbpsL5SCocOSY76r1Q4ZHip6R2aEq0zFc34tI3zHQN0r2Qs3dedzcQKTKUoA4dCD/rbAsuIVXHEzpavvd+QdK8GbcNulOpvYrRaDw52rppAnFlaPbSoHPfmnsjyBAUvZjYGEZydyMTvA1xMyFJdqFxYYc5MuVB7s9obee6IoY7x4ygzDJ2laBRyzY6kie7iIh0fkTYKHwjZB03PoVSB+gCCdNMogaHIH2Sq72Qk1Ip/Emj66dWftPnI1EA5G3Z415QFZX+waM/9khoSPkQqhxu1OQfyGhOkWwo5NQ2f6aI0hhCQoys+eIEUTiBVpLSKcxwRWA/M82uqVHIiRtTtsaNcWeMpmqEUemGAAhk7MTtfFdJAdsFzDYFeyjFX3nsbctTz27clyw9HHFhWGUp+OMv7IkgIOzjJt42ZZVh6kfY51z8GQqUgrn8yy3I/npROWHT2/SaYoKmx+I6cF6iOwg==
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: test
