---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: test
spec:
  encryptedData:
    dbpassword: AgAI22L3Igv/4GW/Zt2u0w3ab3PB7s0ab4dt2IvTlYh4vJ7jSMGExCK3n3Y7ivtlV2FrYVFDorcE0AusF4ljaUVuU2ktO5OW0DomiTGKiAYdZmykp9Lb1/v4QlbADcu/L0RqfUQM68YKS/uVKzMq6DoCsurQIybSFaJGJVTAzclDzPyc8lrhFjNwLOgq+MTV5D84yq98eUA5cZ3h25pKy+BT9NxBqz/e+D95p53LboP0yb7wzrkJKCP+0ICvoMN4KYyzrZRNbYrRDUQokqoSmmtrthwAN+ZUv2ddmsYHaLsow8X1y1NHGmcB1la8Io+L3Vpzdw/VwSAsYkbcTu+SoZao2tpvk0ZcwXwALIrZ+yzOLd9DmPIAoJcWYudMkm48o1sI98DxsiONGvhrcQftrevKYTbeOmYGERvi0bGNvb7awVYaH3LmYc+bH7M1CskjkEWdZNaalhRei9yLcV5geMlsK/sdvNvPlw1XnFXjSrMQTFGQRFYep/2pmD6B0BogPtkGZ7rv8aVLodI0x1MSQYExIc6lb7OPmP7IVes1mYKHwN1haii7K13cCyu3EnPQzGsJdA1VfmxITgEukkqps1I8gmBY5DytQq1uOU0NSe2uibEGxzEug6mSWi+0mIYcbj3apydOd2N7U2Rt14hDKyfMhv3j2plQE6NsecEA4DKKZ9g/BiTN6p5Rn76vLFrZKw2kKhJgSnUtPA==
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: test
