---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test
  namespace: test
spec:
  encryptedData:
    dbpassword: AgAD/uCdmEMBEJS1WyUeE5DlNn9w/fxxHH+pXpsN6gPyjoC8HEoMhRbJ5mkr8ylZWcMaCPookrMkSAt3bpN79tFxbxTEAYOOi7hfo13FOZzsWd/YUPRJWXwlsPAXfMDe7k9qAitWRl4dEhOr8lgROnL2Gkljw2zWXkkRCD6Ylo+ffATpp4Js2yAuU2ZQHPLwsnY1usOhmi8XEamxmV+PWeipeNi89Vnvb+blQXGBAEqlyRBUj4iuTTS3cPTTBE96qlw0ChZC+HS1nYlhlrYLf1n1juom4EUWfbG/y0r1JzY6dJ6EoqWx4ZkNA5FsHGbEGYuRZCZZ3MGPuMhEL6HUsM8qJQTNTXbM/3u9arSrJ9aSmtpM05QQ+iwsIS8llfoZoPg/JCYPc/sQ5nruIXeI2bg2lNr1RZhgVv7CvSNvdoiOiZvC6k4D4XGa4mc6hqt+N8ZBWxYFEWxj26+iZW5cS4t/p6dfB6oSYRb2hGOStUHxCYAIIMleht1tz6xMYtTg5DiFP9GQsK1sqsmm2Q73JwsvKAHbruU30eFTMu8lDK+cUEx9tume5K/Zf1KK+UZy6VWshxF9mLXZzUKqgxx02qhC0nsbzqAyjDcAf4WB9v9rQWFOxHWHVbVJZCfisqziEL3+wrehvZlX69F8qRsTg14R6dpRx187KAT0arOiFZ+QJyM5EFBs9Fea64PxzVDKnTmJj0sW7i1hJw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test
      namespace: test
