---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: test
spec:
  encryptedData:
    dbpassword: AgBuCj9XDDHonS9rg1czypJi+i5zLObKy+cFIRTgutZ2EnQJlFVy7mQxW7ZQWNZ3CCat5I92++gp2/wk1slZV6D1xA8kEs/EblLL9p6lSkAuc90vwBNn86xpTaqZ8nOumBWy13UzE70y0uVM6ibj7nbokGZNmOHekPkSlrxIHzBFp9CmnEAhUIaSP3NDxGS+jTFGEU4zxByhboPD9qI+qsFEUFV7LFHzGWeaXLyR42KbnPAZEQeqYX2QXgRTWJGzcfXqUl74fo89eAJhWjv1Fwyk4qBXFjByUvs8j7rY00ET1GYDnyid7fpHuR4icVDRhJpjPAPq8xSenTs0jpJVTvoHO72Kb5zVL4ImO/rXNm3E8VBW62aCrj2iNFaJURcc8fDw55vSW213nbw6katTVph1B+xZtHieRyakAa2fK2HODSk2MHBhwr8tLctC0K7zM5erBfRi7XS0AGSq1U0CNmJC6TO35BeQrp/Yq0m5QiqVnVhucyphIhJ3AP6vIi/9JIXWet0xrw6o/8f3k6Dny+ccmqjViVe8Qhr8SpnnIa6NhLs39YGHYYie866Lp+sPsY/HrUpNMaiffvXgUY+3aB7YHM6LcoNFpjDqvPRwCWF5kZ+r8RxIHFS1Tpkrd3dPO6DHkGkOVjkieRNKeUDOWOXDkXkO0XPOe7ymgrqkAysv3dUDnTd70Kmx6pekjmcRlVbg6cXBseKW5w==
  template:
    metadata:
      creationTimestamp: null
      name: test
      namespace: test
